In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('D://tram/dataset (1)/train.csv', nrows = 5, sep=';')

In [7]:
def round_time_up_to_hour(time_value):
    hour, minute = map(int, str(time_value).split(':')[:2])
    return hour + (minute > 0)

In [8]:
df.head()

,tran_no,device_no,tran_date_time,begin_date_time,input_date_time,crd_hashcode,validation_result,tran_type_id,place_id,good_type,pass_route,ngpt_route,bus_exit_no,garage_number
0,23480,1734655,2025-01-01 18:17:55,2025-01-01 18:18:00,2025-01-01 18:18:43,6d0d8201efa24f884e70e6f73703b581,1,52,39707,30 дней,НГПТ,25 трамвай,205,31117
1,23481,1734655,2025-01-01 18:17:58,2025-01-01 18:18:00,2025-01-01 18:18:43,1ed503ef82c598fcdc6075650106a86f,1,52,39707,30 дней,НГПТ,25 трамвай,205,31117
2,27701,1736716,2025-01-01 06:03:04,2025-01-01 06:04:00,2025-01-01 06:03:52,e6bbc588d3c24a28a419e50aaa803223,1,52,39707,90 дней,НГПТ,25 трамвай,201,31046
3,25208,1736314,2025-01-01 06:24:42,2025-01-01 06:24:00,2025-01-01 06:25:43,b2f48fc83a0d4e344115d76955af01d5,1,52,39707,СКМ МГТ,NaN,25 трамвай,201,31046
4,13657,1736745,2025-01-01 06:25:43,2025-01-01 06:25:00,2025-01-01 06:26:22,6f6022eae68a6456c0139af93af8157a,1,52,39707,СКМ МГТ,NaN,25 трамвай,204,31121

In [9]:
df['ngpt_route'] = df['ngpt_route'].apply(lambda x: list(x.split())[0])
day = df['tran_date_time'].apply(lambda x: list(x.split())[0])
time = df['tran_date_time'].apply(lambda x: list(x.split())[1])
time = time.apply(round_time_up_to_hour)
df.insert(0, "Day", day)
df.insert(1, "Time", time)
df = df.drop('tran_date_time', axis = 1)

In [10]:
df['Day'] = df['Day'].apply(lambda x: x.replace('-','.'))

In [11]:
df.head()

,Day,Time,tran_no,device_no,begin_date_time,input_date_time,crd_hashcode,validation_result,tran_type_id,place_id,good_type,pass_route,ngpt_route,bus_exit_no,garage_number
0,2025.01.01,19,23480,1734655,2025-01-01 18:18:00,2025-01-01 18:18:43,6d0d8201efa24f884e70e6f73703b581,1,52,39707,30 дней,НГПТ,25,205,31117
1,2025.01.01,19,23481,1734655,2025-01-01 18:18:00,2025-01-01 18:18:43,1ed503ef82c598fcdc6075650106a86f,1,52,39707,30 дней,НГПТ,25,205,31117
2,2025.01.01,7,27701,1736716,2025-01-01 06:04:00,2025-01-01 06:03:52,e6bbc588d3c24a28a419e50aaa803223,1,52,39707,90 дней,НГПТ,25,201,31046
3,2025.01.01,7,25208,1736314,2025-01-01 06:24:00,2025-01-01 06:25:43,b2f48fc83a0d4e344115d76955af01d5,1,52,39707,СКМ МГТ,NaN,25,201,31046
4,2025.01.01,7,13657,1736745,2025-01-01 06:25:00,2025-01-01 06:26:22,6f6022eae68a6456c0139af93af8157a,1,52,39707,СКМ МГТ,NaN,25,204,31121